name: Test Server CI

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: [3.9]
        node-version: [16.17.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - run: npm ci
      - run: cat src/jest/test.env > .env
      - run: npm run build --if-present
      - run: npm test
        env:
          PORT: 3000
